baseURL = "http://thedatascoop.netlify.com/"
languageCode = "en-us"
title = "The Data Scoop"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-141260929-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
  
[params]
  favicon = "/images/favicon.ico"
  description = "Telling Stories With Data"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/lena-han"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/lena-han/"
  #mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/nyc.png"
  recent_posts_number = 3
  
 [taxonomies]
 category = "categories"
